In [2]:
import math

import tensorflow as tf
import numpy as np

In [30]:
tf.__version__

'2.10.1'

In [31]:
dummy_scalar = tf.constant(7)
dummy_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [32]:
dummy_scalar.ndim

0

In [33]:
dummy_vector = tf.constant([10,11])
dummy_vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11])>

In [34]:
dummy_vector.ndim

1

In [35]:
dummy_matrix = tf.constant([[1,2,3],
                            [4,5,6]])
dummy_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [36]:
dummy_matrix.ndim

2

In [37]:
dummy_matrix1 = tf.constant([[1.,2.,4.],
                            [4.,5.,6.]], dtype=tf.float32)
dummy_matrix1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 4.],
       [4., 5., 6.]], dtype=float32)>

In [38]:
dummy_matrix1.ndim

2

In [39]:
tensor = tf.constant([[[10, 11, 12],
                       [13, 14 ,15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])>

In [40]:
tensor.ndim

3

In [41]:
#Changeable Tensor
updatable_tensor = tf.Variable([6, 9])
updatable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 9])>

In [42]:
updatable_tensor[0] = 11


TypeError: 'ResourceVariable' object does not support item assignment

In [44]:
updatable_tensor[0].assign(69)
updatable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([69,  9])>

In [45]:
#Random Tensors
random_tensor1 = tf.random.Generator.from_seed(420)
random_tensor1 = random_tensor1.normal(shape=(3, 2))

random_tensor2 = tf.random.Generator.from_seed(420)
random_tensor2 = random_tensor2.normal(shape=(3, 2))
random_tensor1, random_tensor2, random_tensor2 == random_tensor1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6356361 , -0.08795371],
        [-1.3398387 , -0.00641572],
        [-1.1475449 ,  0.6519857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6356361 , -0.08795371],
        [-1.3398387 , -0.00641572],
        [-1.1475449 ,  0.6519857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [46]:
#Shuffle a tensor
to_be_shuffled = tf.constant([[1, 2],
                              [3, 4],
                              [5, 6]])
to_be_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [47]:
tf.random.set_seed(69)
tf.random.shuffle(to_be_shuffled, seed= 69)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]])>

In [48]:
tf.random.set_seed(42)
tf.random.shuffle(to_be_shuffled, seed= 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [49]:
tf.ones(shape=(3, 2), dtype=  tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [50]:
numpy_array = np.arange(1, 25, dtype = np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [51]:
tensor_from_np = tf.constant(numpy_array, shape = (2, 4, 3))
tensor_from_np

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [52]:
tf.size(tensor_from_np).numpy()

24

In [53]:
tensor_from_np[0]

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [54]:
rank_4_tensors = tf.zeros(shape = [2,3,4,5], dtype = tf.int32)
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])>

In [55]:
rank_4_tensors[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]])>

In [56]:
rank_2_tensor = tf.constant([[10, 7], 
                             [3, 4]])
rank_2_tensor.ndim

2

In [57]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [58]:
#add dim to rank 2
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [59]:
#ALternative to tf.new-axis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [62]:
#Tensor matrix Multiplication
tensor1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
tensor2 = tf.constant([[3, 5], 
                       [6, 7], 
                       [1, 8]])
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [61]:
tensor1 * tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [63]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [65]:
tf.transpose(tensor2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]])>

In [67]:
tf.reshape(tensor2, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]])>

In [3]:
t1 = tf.constant([10, 11])
t1.dtype

tf.int32

In [4]:
tf.cast(t1, dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([10, 11], dtype=int16)>

In [6]:
#Aggregation on tensors
d = tf.constant([-1, 2])
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [10]:
random1 = tf.constant(np.random.randint(0, 100, size=50))
random1

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([68, 72, 95, 14, 40, 27, 33, 59, 50,  6, 85, 84,  7, 35, 92,  3, 43,
       43, 80, 68, 28, 95, 10, 24,  6, 79, 36, 81, 91,  3, 91, 31, 49, 57,
       96, 37, 48, 53, 18, 18, 33, 69, 39, 96, 25, 26, 66, 46, 94, 49])>

In [11]:
tf.reduce_min(random1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [12]:
tf.reduce_max(random1)

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [43]:
tf.reduce_mean(random1)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [44]:
tf.reduce_sum(random1)

<tf.Tensor: shape=(), dtype=int32, numpy=2498>

In [125]:
mean_random1 = tf.reduce_mean(random1)
variance = tf.reduce_sum((random1 - mean_random1) * (random1 - mean_random1))/50
variance

<tf.Tensor: shape=(), dtype=float64, numpy=844.08>

In [129]:
import math
standard_dev = math.sqrt(variance)
standard_dev

29.053054916824152

In [110]:
tf.math.reduce_std(tf.cast(random1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.037191>

In [117]:
tf.math.reduce_variance(tf.cast(random1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=843.15845>

In [150]:
random1[tf.argmax(random1)]

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [162]:
random1[tf.argmin(random1)]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [163]:
#Sqeeze tensor

tensorZ = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1,50))
tensorZ

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.0832541 , 0.99248636, 0.82938504, 0.08254564, 0.34353828,
          0.9793204 , 0.40720654, 0.0583508 , 0.43135   , 0.5283692 ,
          0.6364182 , 0.5932324 , 0.40133286, 0.22207582, 0.9583082 ,
          0.759742  , 0.600194  , 0.56783664, 0.6570866 , 0.025051  ,
          0.7066394 , 0.33194077, 0.56987965, 0.22102642, 0.7593223 ,
          0.7941127 , 0.09434187, 0.52985823, 0.42190957, 0.3904456 ,
          0.03767717, 0.19537008, 0.6503105 , 0.53545094, 0.50305116,
          0.94039905, 0.8053868 , 0.96903086, 0.8989762 , 0.41862512,
          0.9306295 , 0.25466585, 0.42837965, 0.47199476, 0.68350816,
          0.7476344 , 0.23509991, 0.9566351 , 0.15027404, 0.05724108]]]],
      dtype=float32)>

In [165]:
tensorZ.shape

TensorShape([1, 1, 1, 50])

In [166]:
tf.squeeze(tensorZ)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.0832541 , 0.99248636, 0.82938504, 0.08254564, 0.34353828,
       0.9793204 , 0.40720654, 0.0583508 , 0.43135   , 0.5283692 ,
       0.6364182 , 0.5932324 , 0.40133286, 0.22207582, 0.9583082 ,
       0.759742  , 0.600194  , 0.56783664, 0.6570866 , 0.025051  ,
       0.7066394 , 0.33194077, 0.56987965, 0.22102642, 0.7593223 ,
       0.7941127 , 0.09434187, 0.52985823, 0.42190957, 0.3904456 ,
       0.03767717, 0.19537008, 0.6503105 , 0.53545094, 0.50305116,
       0.94039905, 0.8053868 , 0.96903086, 0.8989762 , 0.41862512,
       0.9306295 , 0.25466585, 0.42837965, 0.47199476, 0.68350816,
       0.7476344 , 0.23509991, 0.9566351 , 0.15027404, 0.05724108],
      dtype=float32)>

In [172]:
#ONE HOT ENCODING
lists = [0, 1, 2, 3, 4, 5]
tf.one_hot(lists, 6, on_value="Dead", off_value="Alive")

<tf.Tensor: shape=(6, 6), dtype=string, numpy=
array([[b'Dead', b'Alive', b'Alive', b'Alive', b'Alive', b'Alive'],
       [b'Alive', b'Dead', b'Alive', b'Alive', b'Alive', b'Alive'],
       [b'Alive', b'Alive', b'Dead', b'Alive', b'Alive', b'Alive'],
       [b'Alive', b'Alive', b'Alive', b'Dead', b'Alive', b'Alive'],
       [b'Alive', b'Alive', b'Alive', b'Alive', b'Dead', b'Alive'],
       [b'Alive', b'Alive', b'Alive', b'Alive', b'Alive', b'Dead']],
      dtype=object)>

In [173]:
tf.square(random1)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([4624, 5184, 9025,  196, 1600,  729, 1089, 3481, 2500,   36, 7225,
       7056,   49, 1225, 8464,    9, 1849, 1849, 6400, 4624,  784, 9025,
        100,  576,   36, 6241, 1296, 6561, 8281,    9, 8281,  961, 2401,
       3249, 9216, 1369, 2304, 2809,  324,  324, 1089, 4761, 1521, 9216,
        625,  676, 4356, 2116, 8836, 2401])>